<?php
error_reporting(E_ALL);
ini_set('display_errors', TRUE);
ini_set('display_startup_errors', TRUE);

// CModels
module_load_include('inc', 'islandora_bioinformatics', 'includes/cmodel_helper_functions');

// Islandora hook implementations
module_load_include('inc', 'islandora_bioinformatics', 'includes/hook_view_object');
module_load_include('inc', 'islandora_bioinformatics', 'includes/hook_ingest_steps');

// Access
module_load_include('inc', 'islandora_bioinformatics', 'includes/access_callbacks');

// Drupal Forms
module_load_include('inc', 'islandora_bioinformatics', 'forms/related_objects.form');
module_load_include('inc', 'islandora_bioinformatics', 'forms/project_assign_person.form');

// Page Callbacks
module_load_include('inc', 'islandora_bioinformatics', 'includes/page_callbacks');

/**
 * Implements hook_menu()
 *
 * RELATED CONTENT
 * 1. islandora/object/%islandora_object/related_content
 * 2. islandora/object/%islandora_object/related_content/add/%islandora_cmodel
 * 3. islandora/object/%islandora_object/related_content/ingest/%islandora_cmodel
 *
 * MNPL
 * 1. islandora/object/%islandora_object/people
 */
function islandora_bioinformatics_menu(){
  $urls = array();

  // Default Functionality
  $urls['islandora/object/%islandora_object/related_content'] = array(
    'title' => 'Related Content',
    'page callback' => 'islandora_related_objects_page',
    'page arguments' => array(2),
    'access callback' => 'islandora_related_objects_page_access',
    'access arguments' => array(2),
    'type' => MENU_LOCAL_TASK,
  );

  $urls['islandora/object/%islandora_object/related_content/add/%islandora_cmodel'] = array(
    'title callback' => 'islandora_cmodel_function_title',
    'title arguments' => array('Add', 5),
    'page callback' => 'islandora_related_objects_add_callback',
    'page arguments' => array(2, 5),
    'access callback' => 'islandora_object_access',
    'access arguments' => array(FEDORA_METADATA_EDIT, 2),
    'type' => MENU_CALLBACK,
  );

  $urls['islandora/object/%islandora_object/related_content/ingest/%islandora_cmodel'] = array(
    'title callback' => 'islandora_cmodel_function_title',
    'title arguments' => array('Ingest', 5),
    'page callback' => 'islandora_related_objects_ingest_callback',
    'page arguments' => array(2, 5),
    'access callback' => 'islandora_object_access',
    'access arguments' => array(FEDORA_INGEST, 2),
    'type' => MENU_CALLBACK,
  );

  // Custom Tab
  $urls['islandora/object/%islandora_object/people'] = array(
    'title' => 'People',
    'type' => MENU_LOCAL_TASK,
    'description' => 'People assigned to this project.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_related_objects_form', 2, 'islandora:person_cmodel'),
    'access callback' => 'islandora_related_people_access',
    'access arguments' => array(array(FEDORA_VIEW_OBJECTS), 2),
  );

  return $urls;
}

function islandora_cmodel_function_title($action, $cmodel){
  return "{$action} {$cmodel->label}";
}

/**
 * Implements hook_theme()
 *
 * MNPL
 *
 * Themes
 *  1. islandora_lab_object
 *  2. islandora_project
 *  3. islandora_person
 *
 */
function islandora_bioinformatics_theme($existing, $type, $theme, $path) {
  $themes = array();

  $themes['islandora_lab_object'] = array(
    'file' => 'theme/theme.inc',
    'template' => 'theme/islandora_lab_object',
    'variables' => array(
      'object' => NULL,
    ),
  );

  $themes['islandora_project']    = array(
    'file' => 'theme/theme.inc',
    'template' => 'theme/islandora_project',
    'variables' => array(
      'object' => NULL,
    ),
  );

  $themes['islandora_person']     = array(
    'file' => 'theme/theme.inc',
    'template' => 'theme/islandora_person',
    'variables' => array(
      'object' => NULL,
    ),
  );

  $themes['cmodel'] = array(
    'file' => 'theme/theme.inc',
    'template' => 'theme/cmodel',
    'variables' => array(
      'object' => NULL,
    ),
  );

  return $themes;
}

/**
 * Implements hook_islandora_required_objects()
 *
 * MNPL
 *
 *  Content Models
 *    1. Lab Object
 *    2. Person
 *    3. Project
 *
 *  Collections
 *    1. Lab Objects
 *    2. Persons
 *    3. Projects
 */
function islandora_bioinformatics_islandora_required_objects(IslandoraTuque  $connection) {
  $module_path = drupal_get_path('module', 'islandora_bioinformatics');

  $objects = array();

  // Constructing CModels
  //                                      PID                               LABEL       DS-COMPOSITE-MODEL PATH
  $lab_object = islandora_cmodel_create('islandora:lab_object_cmodel',  'Lab Object', "$module_path/xml/cmodels/lab_object_dscm.xml");
  $project    = islandora_cmodel_create('islandora:project_cmodel',     'Project',    "$module_path/xml/cmodels/project_dscm.xml");
  $person     = islandora_cmodel_create('islandora:person_cmodel',      'Person',     "$module_path/xml/cmodels/person_dscm.xml");

  // CModel: person isMemberOf project
  islandora_cmodel_add_relationship($person, FEDORA_RELS_EXT_URI, 'isMemberOf', $project->id, FALSE);

  $objects[] = $lab_object;
  $objects[] = $project;
  $objects[] = $person;

  // Collections
  $collections = array(
    'person_collection'     => array( 'parent' => 'islandora:root', 'label'  => 'People', ),
    'project_collection'    => array( 'parent' => 'islandora:root', 'label'  => 'Projects', ),
    'lab_object_collection' => array( 'parent' => 'islandora:root', 'label'  => 'Lab Objects'
    ),
  );

  foreach($collections as $pid => $details){
    // Construct the Fedora Object.
    $collection = $connection->repository->constructObject('islandora:' . $pid);
    $collection->owner = 'fedoraAdmin';
    $collection->label = $details['label'];
    $collection->models = 'islandora:collectionCModel';
    $collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', $details['parent']);

    // Create the COLLECTION_POLICY datastream
    $collection_policy = $collection->constructDatastream ('COLLECTION_POLICY', 'X');
    $collection_policy->mimetype = 'text/xml';
    $collection_policy->setContentFromFile("$module_path/xml/collections/{$pid}_policy.xml", FALSE);

    // Ingest the datastream
    $collection->ingestDatastream($collection_policy);

    // Add collection to the list of objects.
    $objects[] = $collection;
  }

  return array(
    'islandora_bioinformatics' => array(
      'title' => 'Islandora Bioinformatics',
      'objects' => $objects,
    )
  );
}


/**
 * Implements hook_islandora_xml_form_builder_forms()
 *
 * MADS Forms
 *
 *    1. Person MADS Form
 *    2. Project MADS Form
 */
function islandora_bioinformatics_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_bioinformatics');

  // Person Forms
  $fb_forms['Person MADS Form'] = array(
    'form_file' => "$module_path/xml/forms/person_mads_form.xml",
  );

  // Project Forms
  $fb_forms['Project MADS Form'] = array(
    'form_file' => "$module_path/xml/forms/project_mads_form.xml",
  );


  /** @todo Person EML form. */
  /** @todo Person MADS to EML XSLT. */
  /** @todo Project EML form. */
  /** @todo Project MADS to EML XSLT. */

  return $fb_forms;
}

/**
 * Implements hook_islandora_xml_form_builder_form_associations()
 *
 * MNPL
 *
 *   |      CONTENT MODEL        |      FORM BUILDER FORM  |
 *   |-----------------------------------------------------|
 *   | islandora:person_cmodel   |      Person MADS Form   |
 *   | islanodra:project_cmodel  |      Project MADS Form  |
 *
 *
 */
function islandora_bioinformatics_islandora_xml_form_builder_form_associations() {
  $module_path = drupal_get_path('module', 'islandora_bioinformatics');

  $form_associations['islandora_bioinformatics_person_mads'] = array(
    'content_model' => 'islandora:person_cmodel',
    'form_name' => 'Person MADS Form',
    'dsid' => 'MADS',
    'title_field' => array('authority', 'titleInfo', 'title'),
    'transform' => 'No Transform',
    'template' => '',
  );

  $form_associations['islandora_bioinformatics_project_mads'] = array(
    'content_model' => 'islandora:project_cmodel',
    'form_name' => 'Project MADS Form',
    'dsid' => 'MADS',
    'title_field' => array('authority', 'titleInfo', 'title'),
    'transform' => 'No Transform',
    'template' => '',
  );

  return $form_associations;
}

//
/**
 * Implements hook_islandora_object_alter
 *
 * SUBTYPING - Required
 *
 * This function creates a fedora:hasModel relationship between the $object
 * and all of it's CModel's supertypes. Should not be run for CModels.
 */
function islandora_bioinformatics_islandora_object_alter($object, array &$context) {
  $object_is_cmodel = $object->relationships->get(FEDORA_MODEL_URI, 'hasModel', 'fedora-system:ContentModel-3.0');
  if(!$object_is_cmodel){
    // Parent CModel
    $cmodel_id = $object->models[0];
    $models = array_merge($object->models, islandora_cmodel_supertypes($cmodel_id));
    $object->models = $models;

    // Creates a hasParentModel relationship towards the CModel initially chosen.
    $object->relationships->add(ISLANDORA_MODEL_URI, 'hasParentModel', $cmodel_id);
  }
}




//////// PAGE AND FORM ALTERS ///////////
/**
 * Implements hook_islandora_related_objects_page_alter()
 *
 * MNPL
 *
 * Altering the Related Content page for Project's to exclude relationships
 * towards the Person CModel.
 */
function islandora_bioinformatics_islandora_islandora_project_cmodel_related_objects_page_alter(&$page, &$page_state){
  $count = 0;
  foreach($page_state['relationships'] as $rel){
    if($rel['object']['value'] == 'islandora:person_cmodel') {
      unset($page_state['relationships'][$count]);
    }
    $count++;
  }

//  module_load_include('inc', 'islandora_xml_forms', 'builder/includes/associations');
//  var_dump(
//    xml_form_builder_get_associations(
//      array(),
//      array('islandora:person_cmodel'),
//      array(),
//      TRUE
//    )
//  );
}

/**
 * Implements hook_form_islandora_related_objects_form_alter()
 *
 * RELATED CONTENT - Required.
 *
 * Dynamically calls three hooks for altering a related content form:
 *
 *  1. form_islandora_OBJECT_CMODEL_related_objects_form
 *  2. form_islandora_related_RELATED_CMODEL_objects_form
 *  3. form_islandora_OBJECT_CMODEL_related_RELATED_CMODEL_objects_formo
 *
 * Each of these hooks are inherited. So if A is a supertype of B then
 * 'hook_form_islandora_A_related_objects_form_alter()' will also affect
 * the form for B.
 */
function islandora_bioinformatics_form_islandora_related_objects_form_alter(&$form, &$formstate){
  $hooks = array();

  $object = islandora_object_load($formstate['islandora']['object']);
  $related_cmodel_id = $formstate['islandora']['cmodel'];

  $related_cmodel_types = array_merge(array($related_cmodel_id),
                                      islandora_cmodel_supertypes($related_cmodel_id));

  $rcm_count = 0;
  foreach($related_cmodel_types as $rcm){
    // Replace : with _ for hook name generation.
    $rcm_str_replaced  = str_replace(':', '_', $rcm);

    // Replace it in the array.
    $related_cmodel_types[$rcm_count] = $rcm_str_replaced;

    $hooks[] = "form_islandora_related_{$rcm_str_replaced}_objects_form";
    $rcm_count++;
  }


  $object_models = array_diff($object->models, array('fedora-system:FedoraObject-3.0'));
  foreach($object_models as $ocm){
    $object_cmodel = str_replace(':', '_', $ocm);
    $hooks[] = "form_islandora_{$object_cmodel}_related_objects_form";

    foreach($related_cmodel_types as $rcm){
      $hooks[] = "form_islandora_{$object_cmodel}_related_{$rcm}_objects_form";
    }
  }

//  echo '<pre>';
//  var_dump($hooks);
//  echo '</pre>';

  drupal_alter($hooks, $form, $formstate);

}

/** Implements hook_form_islandora_related_RELATED_CMODEL_objects_form_alter */
function islandora_bioinformatics_form_islandora_related_islandora_person_cmodel_objects_form_alter(&$form, &$form_state) {
  /**
   * @author Nolan Phillips ncphillips@upei.ca
   *
   * @param $form
   * @param $form_state
   * @return form array $form
   *
   * Implements hook_related_people_form_alter()
   *
   * Alters the related_objects_form for displaying related People.
   */
  module_load_include('inc', 'islandora_bioinformatics', 'includes/mads_to_array');

  $object = $form_state['islandora']['object'];
  $people = $form_state['islandora']['related_objects'];

  $header = array(
    'name' => t('Name'),
    'phone' => t('Phone Number'),
    'email' => t('Email'),
  );

  $form['cmodel']['#markup'] = 'People';

  $form['ingest'] = array();

  $people_entries = array();

  foreach ($people as $person) {
    // Default Values
    if (!isset($person['MADS'])) break;

    $person_mads = person_mads_to_array($person);
    $person_id = $person->id;

    $name = $person_mads['name']['first'] . ' ' . $person_mads['name']['last'];

    $people_entries[$person_id] = array(
      'name' => l($name, "islandora/object/$person_id"),
      'phone' => $person_mads['contact']['phone'],
      'email' => $person_mads['contact']['email'],
    );
  }

  $form['table']['#header'] = $header;
  $form['table']['#options'] = $people_entries;
  $form['table']['#empty'] = t('There is no people related to ' . $object->id . '.');

  return $form;
}
