<?php
/**
 * @file
 * islandora_bioinformatics.install
 */

/**
 * Implements hook_install().
 *
 * @see islandora_bioinformatics_islandora_required_objects()
 */
function islandora_bioinformatics_install() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  islandora_install_solution_pack('islandora_bioinformatics');

  if(!taxonomy_vocabulary_machine_name_load('assay')){
    $assay_vocab = (object) array(
      'name' => 'Assays',
      'descriptions' => 'Assays used by the Marine Natural Products Lab',
      'machine_name' => 'assays',
    );

    taxonomy_vocabulary_save($assay_vocab);
    $vocab = taxonomy_vocabulary_machine_name_load('my_custom_vocab');
    $vid = $vocab->vid;

    $terms = array(
      (object) array('name'=> 'CA', 'description' => 'Candida Albicans', 'vid' => $vid),
      (object) array('name'=> 'EF', 'description' => 'Enterococcus faecalis', 'vid' => $vid),
      (object) array('name'=> 'HC', 'description' => 'HCT116', 'vid' => $vid),
      (object) array('name'=> 'HE', 'description' => 'HELA', 'vid' => $vid),
      (object) array('name'=> 'LO', 'description' => 'Lypoxygenase', 'vid' => $vid),
      (object) array('name'=> 'MD', 'description' => 'Mycobacterium diernhoferi', 'vid' => $vid),
      (object) array('name'=> 'ME', 'description' => 'Mycobacterium smegmatis', 'vid' => $vid),
      (object) array('name'=> 'MF', 'description' => 'Mycobacterium terrae', 'vid' => $vid),
      (object) array('name'=> 'MRSA', 'description' => 'MRSA', 'vid' => $vid),
      (object) array('name'=> 'P1B' , 'description' => 'PTB1B', 'vid' => $vid),
      (object) array('name'=> 'PA' , 'description' => 'Pseudomonas aeruginosa', 'vid' => $vid),
      (object) array('name'=> 'PC' , 'description' => 'PC3', 'vid' => $vid),
      (object) array('name'=> 'SA' , 'description' => 'Staphlococcus aureus', 'vid' => $vid),
      (object) array('name'=> 'VRE' , 'description' => 'VRE', 'vid' => $vid),
    );

    foreach($terms as $term){
      if (taxonomy_get_term_by_name($term->name, 'assays'))
      taxonomy_term_save($term);
    }

  }
}


/**
 * Implements hook_uninstall().
 */
function islandora_bioinformatics_uninstall() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  islandora_install_solution_pack('islandora_bioinformatics', 'uninstall');
  $variables = array('islandora_bioinformatics');
  array_walk($variables, 'variable_del');
}

